version: '3.9'

services:
  tbb-scraper:
    image: tbb-scraper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8224:8224"
    environment:
      BUILD_FROM: ${BUILD_FROM}
      TBB_USERNAME: ${TBB_USERNAME}
      TBB_PASSWORD: ${TBB_PASSWORD}
      TBB_SITE_ID: ${TBB_SITE_ID}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_TOPIC: ${MQTT_TOPIC}